apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.registerApi.name }}-service
  namespace: {{ .Values.registerApi.name }}-{{ .Values.registerApi.env }}
spec:
  selector:
    app: {{ .Values.registerApi.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
