- name: Deploy Playbook
  hosts: node1
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Copy file
      copy:
        src: "{{ workspace }}/kubernetes"
        dest: /opt
        
    - name: Run Shell Script
      command: "bash /opt/kubernetes/helm-chart.sh"
