- name: Deploy Playbook
  hosts: node1
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Run Shell Script
      shell: |
        helm repo add register-app-{{ app_env }} https://nexus-ui.e-crops.co/repository/helm-repo/ --username dara --password 123
        
