- name: Deploy Playbook
  hosts: node1
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Creates directory
      file:
        path: /opt/kubernetes
        state: directory
        recurse: yes
    - name: Copy file
      copy:
        src: "{{ workspace }}/kubernetes"
        dest: /opt/kubernetes
        
    - name: Run Shell Script
      command: "bash /opt/kubernetes/helm-chart.sh"
